import React, { useState, useEffect } from 'react';
import { Loader, FormField, Card } from '../components';

const RenderCards = ({ data, title }) => {
    if(data?.length > 0) {
        return data.map((post) => <Card key={post._id} {...post} />)
    }
    return(
        <h1 className='mt-5 font-bold text-black text-xl uppercase'>{title}</h1>
    )
}

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setSearchText] = useState('abc');

    useEffect(() => {
        const fetchPosts = async() => {
            setLoading(true);

            try {
                const response = await fetch('http://localhost:3000/api/v1/post', {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json'
                    }
                })
                if(response.ok) {
                    const result = await response.json();
                    setAllPosts(result.data.reverse());
                } else {
                    const result = await response.json();
                    alert(result.message);
                }
            } catch (error) {
                alert(error);
            } finally {
                setLoading(false);
            }
        }

    }, [])

  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-black text-[32px]'>The Community Showcase</h1>
            <p className='mt-2 text-[#666e75] text-[22px] min-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by <span className='text-white font-bold text-4xl'>A</span>rt<span className='text-white font-bold text-4xl'>S</span>quirt AI</p>
        </div>
        <div className='mt-16 '>
            <FormField />
        </div>
        <div className='mt-10'>
            {loading ? (
                <div className='flex justify-center items-center'>
                    <Loader />
                </div>
            ) : (
                <>
                    {searchText && (
                        <h2 className='font-medium text-[#666e75] text-xl mb-3'>Showing results for <span className='text-[#222328]'>{searchText}</span></h2>
                    )}
                    <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                        {searchText ? (
                            <RenderCards 
                                data = {[]}
                                title = "No search results found." />
                        ) : (
                            <RenderCards
                                data = {allPosts}
                                title = "No posts found." />
                        )}
                    </div>
                </>
            )}

        </div>
    </section>
  )
}

export default Home
